services:
  website:
    image: ghcr.io/zjx-artcc/website:master
    ports:
      - 3700:3000
    container_name: website
    restart: unless-stopped
  updater:
    image: vainnor/vzdc_website_updater:1.0.1
    depends_on:
      - website
    env_file:
      - .env