name: Bug Report
description:  Did you encounter a bug or unexpected behavior on the website?
labels: ["bug"]
assignees:
  - Vainnor
body:
- type: markdown
  attributes:
    value: |
      To prevent duplicate bug reports, make sure to check open and closed issues to see if a similar issue has already been reported.

- type: input
  id: reporter-cid
  attributes:
    label: Your Vatsim CID
    description: It is your Vatsim login. Required for us to contact you in Discord if you're there.
  validations:
    required: true

- type: textarea
  id: what
  attributes:
      label: Description
      description: Please give a brief summary of the problem you encountered.
      value:
  validations:
      required: true

- type: textarea
  id: reproducibility
  attributes:
    label: Minimal Reproduction
    description: Give some brief steps on how to reproduce the bug (e.g. Buttons pressed, pages visited, specific combination of actions etc.).
    value:
  validations:
      required: true

- type: textarea
  id: additional
  attributes:
    label: Additional info
    description: Is there something additional we need to know? Please tell us!
    value:
  validations:
    required: false

- type: checkboxes
  id: validation
  attributes:
    label: Validation
    description: Please validate your report
    options:
      - label: I have searched open/closed issues and did not find any similar bugs
        required: true
