import {LogModel} from "@prisma/client";

export const TRAINING_ONLY_LOG_MODELS: LogModel[] = ["CERTIFICATION", "COMMON_MISTAKE", "CERTIFICATION_TYPE", "LESSON", "LESSON_RUBRIC", "SOLO_CERTIFICATION", "TRAINING_SESSION", "STAFF_POSITION"];