name: Build Test

on:
  pull_request:
    branches:
      - master
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Rename .env.public to .env
        run: mv .env.public .env

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build
        run: npm run build
